import Foundation

// MARK: - Top-level schedule data (loaded from schedules.json)

/// The complete schedule dataset for one operator, generated by pipeline/build.py.
/// All departures use indexed references to `headsigns`, `lineNames`, `routeIds`, `tripIds`
/// for compact storage.
struct ScheduleData: Codable {
    let operator_: OperatorMeta
    let lastUpdated: String
    let validUntil: String
    let headsigns: [String]
    let lineNames: [String]
    let routeIds: [String]
    let tripIds: [String]
    let routes: [Route]
    let stops: [ScheduleStop]
    let stopPatterns: [[String]]?

    enum CodingKeys: String, CodingKey {
        case operator_ = "operator"
        case lastUpdated, validUntil, headsigns, lineNames, routeIds, tripIds
        case routes, stops, stopPatterns
    }
}

struct OperatorMeta: Codable {
    let id: String
    let name: String
    let url: String
}

// MARK: - Route

struct Route: Codable, Identifiable, Hashable {
    static func == (lhs: Route, rhs: Route) -> Bool { lhs.id == rhs.id }
    func hash(into hasher: inout Hasher) { hasher.combine(id) }

    let id: String
    let name: String
    let longName: String
    let color: String
    let textColor: String
    let transitType: TransitType
    let directions: [RouteDirection]
    let url: String?

    private enum CodingKeys: String, CodingKey {
        case id, name, longName, color, textColor, transitType, directions
        case url = "route_url"
    }
}

struct RouteDirection: Codable, Identifiable, Hashable {
    let id: Int
    let headsign: String
    let stopIds: [String]
    let shape: [[Double]]
}

// MARK: - Stop (from schedule JSON)

struct ScheduleStop: Codable, Identifiable {
    let id: String
    let name: String
    let lat: Double
    let lng: Double
    let lines: [String]
    /// Departures grouped by day key (e.g. "mon,tue,wed,thu,fri").
    /// Each departure is a compact array: [time, lineIdx, headsignIdx, dock?, patternIdx?, tripIdIdx?]
    let departures: [String: [[JSONValue]]]
    let docks: [Dock]?
}

struct Dock: Codable, Hashable {
    let letter: String
    let lat: Double
    let lng: Double
    let lines: [String]
}

// MARK: - Transit Type

enum TransitType: String, Codable, CaseIterable {
    case bus
    case tram
    case metro
    case rail
    case ferry
    case cable_tram
    case gondola
    case funicular
    case trolleybus
    case monorail

    var displayName: String {
        switch self {
        case .bus: "Bus"
        case .tram: "Tram"
        case .metro: "Metro"
        case .rail: "Rail"
        case .ferry: "Ferry"
        case .cable_tram: "Cable Tram"
        case .gondola: "Gondola"
        case .funicular: "Funicular"
        case .trolleybus: "Trolleybus"
        case .monorail: "Monorail"
        }
    }

    var icon: LucideIcon {
        switch self {
        case .bus, .trolleybus: .bus
        case .tram, .rail, .monorail: .train
        case .metro: .train  // fallback until trainSubway asset is available
        case .ferry: .ship
        case .cable_tram, .gondola, .funicular: .cableCar
        }
    }
}

// MARK: - JSONValue (for heterogeneous compact departure arrays)

/// Represents a value in the compact departure array format.
/// Elements: [String(time), Int(lineIdx), Int(headsignIdx), String?(dock), Int?(patternIdx), Int?(tripIdIdx)]
enum JSONValue: Codable {
    case string(String)
    case int(Int)
    case double(Double)

    init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
            self = .int(v)
        } else if let v = try? container.decode(Double.self) {
            self = .double(v)
        } else if let v = try? container.decode(String.self) {
            self = .string(v)
        } else {
            self = .string("")
        }
    }

    func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .string(let v): try container.encode(v)
        case .int(let v): try container.encode(v)
        case .double(let v): try container.encode(v)
        }
    }

    var stringValue: String {
        switch self {
        case .string(let v): v
        case .int(let v): String(v)
        case .double(let v): String(v)
        }
    }

    var intValue: Int {
        switch self {
        case .int(let v): v
        case .double(let v): Int(v)
        case .string(let v): Int(v) ?? 0
        }
    }
}
